version: '3.9'

services:
  wordpress:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    ports:
      - ${IP}:80:80 # change ip if required
    volumes:
      - ./volumes/config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./volumes/wordpress:/var/www/html # Full wordpress project
      - ../themes/white-label-headless-wordpress/:/var/www/html/wp-content/themes/white-label-headless-wordpress # Theme development
      - ../packages/wordpress-blocks/:/var/www/html/wp-content/themes/white-label-headless-wordpress/node_modules/@mqs/wordpress-blocks # Theme development
      #- ../plugins/plugin-name/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ../themes/theme-name/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - mysql
    links:
      - mysql

  wordpress_cli:
    image: wordpress:cli
    volumes:
      - ./volumes/config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./volumes/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - mysql
      - wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - ${IP}:8080:80
    links:
      - mysql:mysql

  mysql:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - ${IP}:3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./volumes/data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

volumes:
  db_data:
